package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "example1",
    srcs = ["example1.cpp"],
    deps = [
        "//reflect:expr_struct",
    ],
    linkopts=[],
)

cc_binary(
    name = "example2",
    srcs = ["example2.cpp"],
    deps = [
        "//reflect:expr_struct",
    ],
    linkopts=[],
)