# SubGraph 
[[function]]
nodes = [
    { id = "1", script = "recmd_recall_emb_1.cpp", function = "main_entry" },
    { id = "2", script = "recmd_recall_emb_2.cpp", function = "main_entry" },
    { id = "3", script = "recmd_recall_emb_3.cpp", function = "main_entry" },
    { id = "4", script = "recmd_recall_emb_4.cpp", function = "main_entry" },
    { id = "5", script = "recmd_recall_emb_5.cpp", function = "main_entry" },
    { id = "6", script = "recmd_recall_emb_6.cpp", function = "main_entry" },
    { phase = "recmd_merge", args = "", dependents = ["6", "1", "2", "3", "4", "5"] },
]
name = "concurrent_graph"

[[function]]
nodes = [
    { id = "1", phase = "emb_itemcf_rank_recmd1", args = "retnum=200,source_id=1041,count=60,seq_seed_num=15,satisfy_type=5,dislike_cate_num=3,reason=word2vec_i2i,model_id=r1041,rimos_key=default_version,rimos_desc=1" },
    { id = "2", phase = "emb_itemcf_rank_recmd2", args = "retnum=200,source_id=1041,count=60,seq_seed_num=15,satisfy_type=5,dislike_cate_num=3,reason=word2vec_i2i,model_id=r1041,rimos_key=default_version,rimos_desc=1" },
    { cond = "$ENV.USER_GROUP==zuma_34new", if = ["1"], else = ["2"] },
]
name = "if_graph"


[[function]]
nodes = [
    { id = "1", phase = "phase_start", output = ["v0", "v1"] },
    { id = "2", phase = "phase1", input = ["v0"], output = ["v3"] },
    { id = "3", phase = "phase2", input = ["v1", "v3"], output = ["v4"] },
    { id = "4", phase = "phase3", input = ["v1", "v4"] },
]
name = "data_dep_graph"

[[function]]
nodes = [
    { id = "34new_user", cond = "$ENV.USER_GROUP==zuma_34new" },
    { id = "34old_user", cond = "$ENV.USER_GROUP==zuma_34old" },
    { id = "1", phase = "phase_start", output = ["v0", "v1"] },
    { id = "2", phase = "phase1", input = ["v0"], output = ["v3"] },
    { id = "3", phase = "phase2", input = ["v1"], optional = [{ ifid = "34new_user", data = ["v3"] }] },
    { id = "4", phase = "phase3", optional = [{ ifid = "34old_user", data = ["v3"] }] },
    { id = "5", phase = "phase4", optional = [{ ifid = "34old_user", data = ["v3"] }] },
]
name = "data_cond_graph"
