package(default_visibility = ["//visibility:public"])

cc_library(
    name = "wrdk_config",
    hdrs = ["toml_helper.h"],
    deps = [
        "@com_github_toml11//:toml",
    ],
    includes=["./"],
)