package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ssexpr",
    hdrs = ["spirit_expression.h"],
    srcs = ["spirit_expression.cpp"],
    deps = [
        "//reflect:expr_struct",
    ],
    includes=["./"],
)