package(default_visibility = ["//visibility:public"])

cc_library(
    name = "wrdk_expr",
    hdrs = ["spirit_expression.h"],
    srcs = ["spirit_expression.cpp"],
    deps = [
        "//reflect:wrdk_reflect",
    ],
)