package(default_visibility = ["//visibility:public"])

cc_library(
    name = "wrdk_reflect",
    hdrs = ["expr_struct.h", "expr_struct_helper.h", "expr_macro.h"],
    deps = [
    ],
    includes=["./"],
)